// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "smooth-cursor": {
      name: "smooth-cursor",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/smooth-cursor.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/atasui/smooth-cursor.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "smooth-cursor-demo": {
      name: "smooth-cursor-demo",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/smooth-cursor-demo.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/smooth-cursor-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "stories": {
      name: "stories",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/stories.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/atasui/stories.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "stories-demo": {
      name: "stories-demo",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/stories-demo.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/stories-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
