// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "smooth-cursor": {
      name: "smooth-cursor",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/smooth-cursor.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/atasui/smooth-cursor.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "smooth-cursor-demo": {
      name: "smooth-cursor-demo",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/smooth-cursor-demo.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/smooth-cursor-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast": {
      name: "toast",
      description: "",
      type: "registry:ui",
      registryDependencies: ["https://ui.atastech.com/r/button"],
      files: [{
        path: "registry/default/ui/toast.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toast.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast-demo": {
      name: "toast-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast-with-action": {
      name: "toast-with-action",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-with-action.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-with-action.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast-promise": {
      name: "toast-promise",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-promise.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-promise.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
